/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_lapangan;

/**
 *
 * @author LAPTOP
 */
public class chooseMenu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public chooseMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        btn_kelola_makanan = new javax.swing.JButton();
        btn_kelola_lapangan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuSelection.jpg"))); // NOI18N
        menu.setText("jLabel2");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.setMaximumSize(new java.awt.Dimension(1582, 982));
        menu.setMinimumSize(new java.awt.Dimension(1582, 982));
        menu.setPreferredSize(new java.awt.Dimension(840, 549));
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        btn_kelola_makanan.setText("jButton1");
        btn_kelola_makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kelola_makananActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kelola_makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 290, 310));

        btn_kelola_lapangan.setText("jButton1");
        btn_kelola_lapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kelola_lapanganActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kelola_lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 280, 300));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kelola_makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kelola_makananActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new kelola_makanan().setVisible(true);
        
    }//GEN-LAST:event_btn_kelola_makananActionPerformed

    private void btn_kelola_lapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kelola_lapanganActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new kelola_lapangan().setVisible(true);
    }//GEN-LAST:event_btn_kelola_lapanganActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kelola_lapangan;
    private javax.swing.JButton btn_kelola_makanan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
