/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_lapangan;

import java.awt.Component;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import koneksi.koneksiLury;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class konfirmasi extends javax.swing.JFrame {
koneksiLury con = new koneksiLury();
    
    String id;
    private void tampil(){
        con.tampil(jTable1,"SELECT * FROM transaksilapangan WHERE status = 'Booking' OR status = 'Lunas'");
        
    }
    
    
    
    private void kondisiAwal(){
        txtKodeBooking.setText("");
        txtTanggalMain.setText("");
        jamMulai.setText("");
        jamSelesai.setText("");
        tampil();
    }
    /**
     * Creates new form konfirmasi
     */
    public konfirmasi() {
        initComponents();
        
        tampil();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        txtKodeBooking = new javax.swing.JTextField();
        txtTanggalMain = new javax.swing.JTextField();
        jamMulai = new javax.swing.JTextField();
        jamSelesai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(0);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 740, 150));

        cmbStatus.setBackground(new java.awt.Color(60, 128, 128));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", " " }));
        cmbStatus.setBorder(null);
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 370, 150, -1));

        txtKodeBooking.setEditable(false);
        txtKodeBooking.setBackground(new java.awt.Color(60, 128, 128));
        txtKodeBooking.setForeground(new java.awt.Color(255, 255, 255));
        txtKodeBooking.setBorder(null);
        getContentPane().add(txtKodeBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 20));

        txtTanggalMain.setEditable(false);
        txtTanggalMain.setBackground(new java.awt.Color(60, 128, 128));
        txtTanggalMain.setForeground(new java.awt.Color(255, 255, 255));
        txtTanggalMain.setBorder(null);
        getContentPane().add(txtTanggalMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 455, 150, 20));

        jamMulai.setEditable(false);
        jamMulai.setBackground(new java.awt.Color(60, 128, 128));
        jamMulai.setForeground(new java.awt.Color(255, 255, 255));
        jamMulai.setBorder(null);
        getContentPane().add(jamMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 150, 20));

        jamSelesai.setEditable(false);
        jamSelesai.setBackground(new java.awt.Color(60, 128, 128));
        jamSelesai.setForeground(new java.awt.Color(255, 255, 255));
        jamSelesai.setBorder(null);
        getContentPane().add(jamSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 455, 150, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Konfirmasi (7) (Custom).png"))); // NOI18N
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        btn_cancel.setText("jButton1");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 110, 40));

        btn_confirm.setText("cancel");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 100, 40));

        btn_back.setText("jButton1");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       kondisiAwal();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        try {
            con.Eksekusi("UPDATE `transaksilapangan` SET `status`='"+ cmbStatus.getSelectedItem().toString() +"' WHERE kode_booking LIKE '"+ txtKodeBooking.getText()+"'", "Berhasil Menyimpan Data", 0);
            
        
   
        
        //batas
        try {
                String report = (con.currentDirectory+"\\src\\notadanlaporan\\pelunasan.jrxml");
                 HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("kodeBooking", txtKodeBooking.getText());
//                hash.put("kode_boking", idBooking);                
//                hash.put("tanggalKedua", textField.getText());
     
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con.getConnection());
                JasperViewer.viewReport(JPrint, false);
            } catch (JRException rptexcpt) {
                System.out.println("Program tidak bisa karena : " + rptexcpt);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kondisiAwal();
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x = jTable1.getSelectedRow();
        
        String id = jTable1.getValueAt(x, 0).toString();
        txtKodeBooking.setText(id);
        txtTanggalMain.setText(jTable1.getValueAt(x, 5).toString());
        jamMulai.setText(jTable1.getValueAt(x, 6).toString());
        jamSelesai.setText(jTable1.getValueAt(x, 7).toString());
        
        String status = jTable1.getValueAt(x, 10).toString();
        
        switch (status){
            case "Lunas":
                cmbStatus.removeAllItems();
                cmbStatus.addItem("Pilih");
                cmbStatus.addItem("Dibatalkan");
                break;
            case "Booking":
                cmbStatus.removeAllItems();
                cmbStatus.addItem("Pilih");
                cmbStatus.addItem("Dibatalkan");
                cmbStatus.addItem("Lunas");
                break;
        }
        
           
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konfirmasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jamMulai;
    private javax.swing.JTextField jamSelesai;
    private javax.swing.JTextField txtKodeBooking;
    private javax.swing.JTextField txtTanggalMain;
    // End of variables declaration//GEN-END:variables
}
