/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_lapangan;

/**
 *
 * @author ASUS
 */
public class transaksi_makanan extends javax.swing.JFrame {

    /**
     * Creates new form transaksi_makanan
     */
    public transaksi_makanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_subTotal = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_total_harga = new javax.swing.JTextField();
        txt_nota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_proses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 127, 740, 170));

        txt_subTotal.setBackground(new java.awt.Color(60, 128, 128));
        txt_subTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_subTotal.setForeground(new java.awt.Color(255, 255, 255));
        txt_subTotal.setBorder(null);
        getContentPane().add(txt_subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 190, 20));

        txt_quantity.setBackground(new java.awt.Color(60, 128, 128));
        txt_quantity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_quantity.setForeground(new java.awt.Color(255, 255, 255));
        txt_quantity.setBorder(null);
        getContentPane().add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 190, 20));

        txt_harga.setBackground(new java.awt.Color(60, 128, 128));
        txt_harga.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(255, 255, 255));
        txt_harga.setBorder(null);
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 190, 20));

        txt_total_harga.setBackground(new java.awt.Color(60, 128, 128));
        txt_total_harga.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_total_harga.setForeground(new java.awt.Color(255, 255, 255));
        txt_total_harga.setBorder(null);
        getContentPane().add(txt_total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 190, 20));

        txt_nota.setBackground(new java.awt.Color(60, 128, 128));
        txt_nota.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_nota.setForeground(new java.awt.Color(255, 255, 255));
        txt_nota.setBorder(null);
        getContentPane().add(txt_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi_makanan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_back.setText("jButton1");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        btn_proses.setText("proses");
        getContentPane().add(btn_proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 90, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi_makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nota;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_subTotal;
    private javax.swing.JTextField txt_total_harga;
    // End of variables declaration//GEN-END:variables
}
